Oss for developper
philippart-s/blog pull request #30
Opened 2021-08-29 07:54 UTC by philippart-s

2021-08-30 11:50 UTC, philippart-s commented
@klaukf aucune obligation de review, c'est si ça t'intéresse.

L'article est visible en recette ici : https://oss-for-developper--oss-for-developper.netlify.app/articles/dev/oss-for-developer/ 😘

2021-08-30 13:30 UTC, klaukf requested changes
Après relecture, je vais me mettre à l'open source !

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +Du coup c'est un peu ardu de trouver le projet qui convienne mais aussi de tenter de comprendre comment le développement est architecturé.A l'origine j'avais jeté mon dévolu sur le plugin Maven mais
```suggestion
Du coup c'est un peu ardu de trouver le projet qui convienne mais aussi de tenter de comprendre comment le développement est architecturé. A l'origine j'avais jeté mon dévolu sur le plugin Maven mais celui-ci utilise JIRA (qui n'est pas très à jour et est complexe), du coup je suis retombé dans le côté ce n'est pas pour moi :flushed:.
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +J'avoue que l'architecture de développement n'est pas forcément clairement expliquée dans les documentations de développeurs des plugins (ou alors je ne l'ai pas trouvé :sweat_smile:).
```suggestion
J'avoue que l'architecture de développement n'est pas forcément clairement expliquée dans les documentations de développeurs des plugins (ou alors je ne l'ai pas trouvée :sweat_smile:).
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +Plugin assez recent avec peu code et surtout pas releasé, cela me permet de bien voir comment est architecturé un plugin Jenkins et aussi d'avoir une petite communauté active.
```suggestion
Plugin assez récent avec peu code et surtout pas releasé, cela me permet de bien voir comment est architecturé un plugin Jenkins et aussi d'avoir une petite communauté active.
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +C'est autre conseil que j'aurai tendance à donner : essayer de trouver un projet d'une taille pas trop grosse qui permet de faciliter sa prise en main mais aussi d'avoir une communauté réduite et don
```suggestion
Cet autre conseil que j'aurai tendance à donner : essayer de trouver un projet d'une taille pas trop grosse qui permet de faciliter sa prise en main mais aussi d'avoir une communauté réduite et donc simple à contacter et identifier (qui fait quoi, notamment les maintainers)
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +C'est quelque chose que je n'avais pas forcément anticipé : les projets Open Source reposent sur le fait que des anonymes offrent du temps personnel pour travailler sur le projet, et le temps personn
```suggestion
C'est quelque chose que je n'avais pas forcément anticipé : les projets Open Source reposent sur le fait que des anonymes offrent du temps personnel pour travailler sur le projet, et le temps personnel par définition une fois enlevé le temps de travail et de sommeil, eh bien il n'en reste pas beaucoup (et je ne parle pas de la vie de famille :wink:).
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +Pour ma part j'y travaille essentiellement le WE, durant les poses déjeuné ou encore en temps partagé devant une série avec ma chérie :kissing_heart:.
```suggestion
Pour ma part j'y travaille essentiellement le WE, durant les pauses déjeuners ou encore en temps partagé devant une série avec ma chérie :kissing_heart:.
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +C'est tout bête mais cela m'a obliger à bien faire attention à mes tournures de phrases pour être sûr de ne pas faire passer le message inverse de ce que je pensais ! :sweat_smile:
```suggestion
C'est tout bête mais cela m'a obligé à bien faire attention à mes tournures de phrases pour être sûr de ne pas faire passer le message inverse de ce que je pensais ! :sweat_smile:
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +J'ai atteins mon premier objectif : reprendre un rythme de développement en Java.
```suggestion
J'ai atteint mon premier objectif : reprendre un rythme de développement en Java.
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +J'ai encore plain d'envies : participer au plugin Maven, au core de Jenkuins, à un projet plus gros, trouver un projet en JDK 11 ou 17, ....
```suggestion
J'ai encore plein d'envies : participer au plugin Maven, au core de Jenkuins, à un projet plus gros, trouver un projet en JDK 11 ou 17, ....
```

2021-08-30 13:30 UTC, klaukf commented on _posts/2021-08-04-oss-for-developer.md
> +En tout cas je vous conseille vraiment de tenter l'expérience, en espérant que je vous ai un peu donnée envie, voir donné quelques astuces.
```suggestion
En tout cas je vous conseille vraiment de tenter l'expérience, en espérant que je vous ai un peu donné envie, voire donné quelques astuces.
```

2021-08-31 11:01 UTC, philippart-s commented
> Après relecture, je vais me mettre à l'open source !

Merci beaucoup du temps passé, je me rends compte que j'avais laissé pas mal de fautes ... désolé 😕

2021-08-31 11:01 UTC, merged